### ISSUE TITLE
得不到json,好像认证失败了

### ISSUE THREAD

**Issue by eric0815** [elainte/zsxq#1]
看了返回的json,状态码是401,请问是什么原因,谢谢

**Comment by elainte** [comment]
不好意思，刚看到，特意试了一下，代码目前还可以运行。
修改以下3个参数
GROUP_ID：（需要自己加入该星球）
user-agent:
cookie: 
原版：https://github.com/96chh/crawl-zsxq，我是根据自己的需求稍微修改一下而已
![QQ截图20190725232924](https://user-images.githubusercontent.com/1108002/61887668-a4d39280-af34-11e9-839a-0da2ff1579b3.png)
